"""Add ON DELETE CASCADE to DocumentTag

Revision ID: d3086a50f658
Revises: 54cc68f240b6
Create Date: 2025-06-20 13:07:52.702867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3086a50f658'
down_revision: Union[str, None] = '54cc68f240b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('document_tags_document_id_fkey'), 'document_tags', type_='foreignkey')
    op.drop_constraint(op.f('document_tags_tag_id_fkey'), 'document_tags', type_='foreignkey')
    op.create_foreign_key(None, 'document_tags', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'document_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_tags', type_='foreignkey')
    op.drop_constraint(None, 'document_tags', type_='foreignkey')
    op.create_foreign_key(op.f('document_tags_tag_id_fkey'), 'document_tags', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key(op.f('document_tags_document_id_fkey'), 'document_tags', 'documents', ['document_id'], ['id'])
    # ### end Alembic commands ###
