"""Add chunk_text to document_embeddings

Revision ID: fb46e1f9b24e
Revises: dc8e889f1401
Create Date: 2025-07-30 14:34:42.780478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb46e1f9b24e'
down_revision: Union[str, None] = 'dc8e889f1401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_embeddings', sa.Column('chunk_text', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_embeddings', 'chunk_text')
    # ### end Alembic commands ###
